/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AdminApiKeyOwner {
  /// The Unix timestamp (in seconds) of when the user was created
  #[serde(rename = "created_at")]
  created_at: Option<i64>,
  /// The identifier, which can be referenced in API endpoints
  #[serde(rename = "id")]
  id: Option<String>,
  /// The name of the user
  #[serde(rename = "name")]
  name: Option<String>,
  /// The object type, which is always organization.user
  #[serde(rename = "object")]
  object: Option<String>,
  /// Always `owner`
  #[serde(rename = "role")]
  role: Option<String>,
  /// Always `user`
  #[serde(rename = "type")]
  _type: Option<String>
}
