/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApproximateLocation {
  #[serde(rename = "city")]
  city: Option<Value>,
  #[serde(rename = "country")]
  country: Option<Value>,
  #[serde(rename = "region")]
  region: Option<Value>,
  #[serde(rename = "timezone")]
  timezone: Option<Value>,
  /// The type of location approximation. Always `approximate`.
  #[serde(rename = "type")]
  _type: String
}
