/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AssistantsNamedToolChoice : Specifies a tool the model should use. Use to force the model to call a specific tool.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AssistantsNamedToolChoice {
  #[serde(rename = "function")]
  function: Option<crate::models::AssistantsNamedToolChoiceFunction>,
  /// The type of the tool. If type is `function`, the function name must be set
  #[serde(rename = "type")]
  _type: String
}
