/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AssistantObjectToolResources : A set of resources that are used by the assistant's tools. The resources are specific to the type of tool. For example, the `code_interpreter` tool requires a list of file IDs, while the `file_search` tool requires a list of vector store IDs.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AssistantObjectToolResources {
  #[serde(rename = "code_interpreter")]
  code_interpreter: Option<crate::models::AssistantObjectToolResourcesCodeInterpreter>,
  #[serde(rename = "file_search")]
  file_search: Option<crate::models::AssistantObjectToolResourcesFileSearch>
}
