/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogActorUser : The user who performed the audit logged action.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogActorUser {
  /// The user email.
  #[serde(rename = "email")]
  email: Option<String>,
  /// The user id.
  #[serde(rename = "id")]
  id: Option<String>
}
