/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogActor : The actor who performed the audit logged action.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogActor {
  #[serde(rename = "api_key")]
  api_key: Option<crate::models::AuditLogActorApiKey>,
  #[serde(rename = "session")]
  session: Option<crate::models::AuditLogActorSession>,
  /// The type of actor. Is either `session` or `api_key`.
  #[serde(rename = "type")]
  _type: Option<String>
}
