/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogProjectUpdated : The details for events with this `type`.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogProjectUpdated {
  #[serde(rename = "changes_requested")]
  changes_requested: Option<crate::models::AuditLogProjectUpdatedChangesRequested>,
  /// The project ID.
  #[serde(rename = "id")]
  id: Option<String>
}
