/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogProjectCreatedData : The payload used to create the project.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogProjectCreatedData {
  /// The project name.
  #[serde(rename = "name")]
  name: Option<String>,
  /// The title of the project as seen on the dashboard.
  #[serde(rename = "title")]
  title: Option<String>
}
