/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogApiKeyCreated : The details for events with this `type`.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogApiKeyCreated {
  #[serde(rename = "data")]
  data: Option<crate::models::AuditLogApiKeyCreatedData>,
  /// The tracking ID of the API key.
  #[serde(rename = "id")]
  id: Option<String>
}
