/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogActorApiKey : The API Key used to perform the audit logged action.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogActorApiKey {
  /// The tracking id of the API key.
  #[serde(rename = "id")]
  id: Option<String>,
  #[serde(rename = "service_account")]
  service_account: Option<crate::models::AuditLogActorServiceAccount>,
  /// The type of API key. Can be either `user` or `service_account`.
  #[serde(rename = "type")]
  _type: Option<String>,
  #[serde(rename = "user")]
  user: Option<crate::models::AuditLogActorUser>
}
