/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogCheckpointPermissionCreatedData : The payload used to create the checkpoint permission.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogCheckpointPermissionCreatedData {
  /// The ID of the fine-tuned model checkpoint.
  #[serde(rename = "fine_tuned_model_checkpoint")]
  fine_tuned_model_checkpoint: Option<String>,
  /// The ID of the project that the checkpoint permission was created for.
  #[serde(rename = "project_id")]
  project_id: Option<String>
}
