/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogLoginFailed : The details for events with this `type`.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogLoginFailed {
  /// The error code of the failure.
  #[serde(rename = "error_code")]
  error_code: Option<String>,
  /// The error message of the failure.
  #[serde(rename = "error_message")]
  error_message: Option<String>
}
