/* 
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogOrganizationUpdatedChangesRequested : The payload used to update the organization settings.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogOrganizationUpdatedChangesRequested {
  /// The organization description.
  #[serde(rename = "description")]
  description: Option<String>,
  /// The organization name.
  #[serde(rename = "name")]
  name: Option<String>,
  #[serde(rename = "settings")]
  settings: Option<crate::models::AuditLogOrganizationUpdatedChangesRequestedSettings>,
  /// The organization title.
  #[serde(rename = "title")]
  title: Option<String>
}
