/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogCertificateDeleted : The details for events with this `type`.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogCertificateDeleted {
  /// The certificate content in PEM format.
  #[serde(rename = "certificate")]
  certificate: Option<String>,
  /// The certificate ID.
  #[serde(rename = "id")]
  id: Option<String>,
  /// The name of the certificate.
  #[serde(rename = "name")]
  name: Option<String>
}
