/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuditLogApiKeyUpdatedChangesRequested : The payload used to update the API key.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogApiKeyUpdatedChangesRequested {
  /// A list of scopes allowed for the API key, e.g. `[\"api.model.request\"]`
  #[serde(rename = "scopes")]
  scopes: Option<Vec<String>>
}
