/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BatchRequestOutputError : For requests that failed with a non-HTTP error, this will contain more information on the cause of the failure.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BatchRequestOutputError {
  /// A machine-readable error code.
  #[serde(rename = "code")]
  code: Option<String>,
  /// A human-readable error message.
  #[serde(rename = "message")]
  message: Option<String>
}
