/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BatchRequestOutputResponse {
  /// The JSON body of the response
  #[serde(rename = "body")]
  body: Option<Value>,
  /// An unique identifier for the OpenAI API request. Please include this request ID when contacting support.
  #[serde(rename = "request_id")]
  request_id: Option<String>,
  /// The HTTP status code of the response
  #[serde(rename = "status_code")]
  status_code: Option<i32>
}
