/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BatchRequestCounts : The request counts for different statuses within the batch.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BatchRequestCounts {
  /// Number of requests that have been completed successfully.
  #[serde(rename = "completed")]
  completed: i32,
  /// Number of requests that have failed.
  #[serde(rename = "failed")]
  failed: i32,
  /// Total number of requests in the batch.
  #[serde(rename = "total")]
  total: i32
}
