/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BatchErrorsData {
  /// An error code identifying the error type.
  #[serde(rename = "code")]
  code: Option<String>,
  /// The line number of the input file where the error occurred, if applicable.
  #[serde(rename = "line")]
  line: Option<i32>,
  /// A human-readable message providing more details about the error.
  #[serde(rename = "message")]
  message: Option<String>,
  /// The name of the parameter that caused the error, if applicable.
  #[serde(rename = "param")]
  param: Option<String>
}
