/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BatchRequestOutput : The per-line object of the batch output and error files

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BatchRequestOutput {
  /// A developer-provided per-request id that will be used to match outputs to inputs.
  #[serde(rename = "custom_id")]
  custom_id: Option<String>,
  #[serde(rename = "error")]
  error: Option<crate::models::BatchRequestOutputError>,
  #[serde(rename = "id")]
  id: Option<String>,
  #[serde(rename = "response")]
  response: Option<crate::models::BatchRequestOutputResponse>
}
