/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CertificateCertificateDetails {
  /// The content of the certificate in PEM format.
  #[serde(rename = "content")]
  content: Option<String>,
  /// The Unix timestamp (in seconds) of when the certificate expires.
  #[serde(rename = "expires_at")]
  expires_at: Option<i32>,
  /// The Unix timestamp (in seconds) of when the certificate becomes valid.
  #[serde(rename = "valid_at")]
  valid_at: Option<i32>
}
