/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionResponseMessageAudio : If the audio output modality is requested, this object contains data about the audio response from the model. [Learn more](/docs/guides/audio).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessageAudio {
  /// Base64 encoded audio bytes generated by the model, in the format specified in the request.
  #[serde(rename = "data")]
  data: String,
  /// The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn conversations.
  #[serde(rename = "expires_at")]
  expires_at: i32,
  /// Unique identifier for this audio response.
  #[serde(rename = "id")]
  id: String,
  /// Transcript of the audio generated by the model.
  #[serde(rename = "transcript")]
  transcript: String
}
