/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCallChunk {
  #[serde(rename = "function")]
  function: Option<crate::models::ChatCompletionMessageToolCallChunkFunction>,
  /// The ID of the tool call.
  #[serde(rename = "id")]
  id: Option<String>,
  #[serde(rename = "index")]
  index: i32,
  /// The type of the tool. Currently, only `function` is supported.
  #[serde(rename = "type")]
  _type: Option<String>
}
