/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequestFunctionMessage {
  /// The contents of the function message.
  #[serde(rename = "content")]
  content: String,
  /// The name of the function to call.
  #[serde(rename = "name")]
  name: String,
  /// The role of the messages author, in this case `function`.
  #[serde(rename = "role")]
  role: String
}
