/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionResponseMessageAnnotations : A URL citation when using web search.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessageAnnotations {
  /// The type of the URL citation. Always `url_citation`.
  #[serde(rename = "type")]
  _type: String,
  #[serde(rename = "url_citation")]
  url_citation: crate::models::ChatCompletionResponseMessageUrlCitation
}
