/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionResponseMessage : A chat completion message generated by the model.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessage {
  /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat).
  #[serde(rename = "annotations")]
  annotations: Option<Vec<crate::models::ChatCompletionResponseMessageAnnotations>>,
  #[serde(rename = "audio")]
  audio: Option<crate::models::ChatCompletionResponseMessageAudio>,
  /// The contents of the message.
  #[serde(rename = "content")]
  content: String,
  #[serde(rename = "function_call")]
  function_call: Option<crate::models::ChatCompletionResponseMessageFunctionCall>,
  /// The refusal message generated by the model.
  #[serde(rename = "refusal")]
  refusal: String,
  /// The role of the author of this message.
  #[serde(rename = "role")]
  role: String,
  #[serde(rename = "tool_calls")]
  tool_calls: Option<crate::models::ChatCompletionMessageToolCalls>
}
