/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionRequestUserMessage : Messages sent by an end user, containing prompts or additional context information.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequestUserMessage {
  /// The contents of the user message.
  #[serde(rename = "content")]
  content: Value,
  /// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
  #[serde(rename = "name")]
  name: Option<String>,
  /// The role of the messages author, in this case `user`.
  #[serde(rename = "role")]
  role: String
}
