/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionRequestMessageContentPartAudio : Learn about [audio inputs](/docs/guides/audio).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequestMessageContentPartAudio {
  #[serde(rename = "input_audio")]
  input_audio: crate::models::ChatCompletionRequestMessageContentPartAudioInputAudio,
  /// The type of the content part. Always `input_audio`.
  #[serde(rename = "type")]
  _type: String
}
