/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequestMessageContentPartAudioInputAudio {
  /// Base64 encoded audio data.
  #[serde(rename = "data")]
  data: String,
  /// The format of the encoded audio data. Currently supports \"wav\" and \"mp3\".
  #[serde(rename = "format")]
  format: String
}
