/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see pub https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec pub version: 2.3.0
 *
 * Generated pub by: https://github.com/swagger-api/swagger-codegen.git
 */

/// pub ChatCompletionStreamResponseDelta : A chat completion delta generated by streamed model responses.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionStreamResponseDelta {
    /// The contents of the chunk message.
    #[serde(rename = "content")]
    pub content: Option<String>,
    #[serde(rename = "function_call")]
    pub function_call: Option<crate::models::ChatCompletionStreamResponseDeltaFunctionCall>,
    /// The refusal message generated by the model.
    #[serde(rename = "refusal")]
    pub refusal: Option<String>,
    /// The role of the author of this message.
    #[serde(rename = "role")]
    pub role: Option<String>,
    #[serde(rename = "tool_calls")]
    pub tool_calls: Option<Vec<crate::models::ChatCompletionMessageToolCallChunk>>,
}
