/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionNamedToolChoice : Specifies a tool the model should use. Use to force the model to call a specific function.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionNamedToolChoice {
  #[serde(rename = "function")]
  function: crate::models::AssistantsNamedToolChoiceFunction,
  /// The type of the tool. Currently, only `function` is supported.
  #[serde(rename = "type")]
  _type: String
}
