/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequestMessageContentPartFileFile {
  /// The base64 encoded file data, used when passing the file to the model  as a string.
  #[serde(rename = "file_data")]
  file_data: Option<String>,
  /// The ID of an uploaded file to use as input.
  #[serde(rename = "file_id")]
  file_id: Option<String>,
  /// The name of the file, used when passing the file to the model as a  string.
  #[serde(rename = "filename")]
  filename: Option<String>
}
