/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCall {
  #[serde(rename = "function")]
  function: crate::models::ChatCompletionMessageToolCallFunction,
  /// The ID of the tool call.
  #[serde(rename = "id")]
  id: String,
  /// The type of the tool. Currently, only `function` is supported.
  #[serde(rename = "type")]
  _type: String
}
