/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionRequestMessageContentPartText : Learn about [text inputs](/docs/guides/text-generation).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequestMessageContentPartText {
  /// The text content.
  #[serde(rename = "text")]
  text: String,
  /// The type of the content part.
  #[serde(rename = "type")]
  _type: String
}
