/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionStreamResponseDelta : A chat completion delta generated by streamed model responses.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionStreamResponseDelta {
  /// The contents of the chunk message.
  #[serde(rename = "content")]
  content: Option<String>,
  #[serde(rename = "function_call")]
  function_call: Option<crate::models::ChatCompletionStreamResponseDeltaFunctionCall>,
  /// The refusal message generated by the model.
  #[serde(rename = "refusal")]
  refusal: Option<String>,
  /// The role of the author of this message.
  #[serde(rename = "role")]
  role: Option<String>,
  #[serde(rename = "tool_calls")]
  tool_calls: Option<Vec<crate::models::ChatCompletionMessageToolCallChunk>>
}
