/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionMessageList : An object representing a list of chat completion messages.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionMessageList {
  /// An array of chat completion message objects.
  #[serde(rename = "data")]
  data: Vec<Value>,
  /// The identifier of the first chat message in the data array.
  #[serde(rename = "first_id")]
  first_id: String,
  /// Indicates whether there are more chat messages available.
  #[serde(rename = "has_more")]
  has_more: bool,
  /// The identifier of the last chat message in the data array.
  #[serde(rename = "last_id")]
  last_id: String,
  /// The type of this object. It is always set to \"list\".
  #[serde(rename = "object")]
  object: String
}
