/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionRequestMessageContentPartFile : Learn about [file inputs](/docs/guides/text) for text generation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequestMessageContentPartFile {
  #[serde(rename = "file")]
  file: crate::models::ChatCompletionRequestMessageContentPartFileFile,
  /// The type of the content part. Always `file`.
  #[serde(rename = "type")]
  _type: String
}
