/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChatCompletionRequestSystemMessage : Developer-provided instructions that the model should follow, regardless of messages sent by the user. With o1 models and newer, use `developer` messages for this purpose instead.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequestSystemMessage {
  /// The contents of the system message.
  #[serde(rename = "content")]
  content: Value,
  /// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
  #[serde(rename = "name")]
  name: Option<String>,
  /// The role of the messages author, in this case `system`.
  #[serde(rename = "role")]
  role: String
}
