/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Click : A click action.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Click {
  /// Indicates which mouse button was pressed during the click. One of `left`, `right`, `wheel`, `back`, or `forward`.
  #[serde(rename = "button")]
  button: String,
  /// Specifies the event type. For a click action, this property is  always set to `click`.
  #[serde(rename = "type")]
  _type: String,
  /// The x-coordinate where the click occurred.
  #[serde(rename = "x")]
  x: i32,
  /// The y-coordinate where the click occurred.
  #[serde(rename = "y")]
  y: i32
}
