/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CodeInterpreterFileOutput : The output of a code interpreter tool call that is a file.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CodeInterpreterFileOutput {
  #[serde(rename = "files")]
  files: Vec<crate::models::CodeInterpreterFileOutputFiles>,
  /// The type of the code interpreter file output. Always `files`.
  #[serde(rename = "type")]
  _type: String
}
