/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CodeInterpreterToolCall : A tool call to run code.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CodeInterpreterToolCall {
  /// The code to run.
  #[serde(rename = "code")]
  code: String,
  /// The unique ID of the code interpreter tool call.
  #[serde(rename = "id")]
  id: String,
  /// The results of the code interpreter tool call.
  #[serde(rename = "results")]
  results: Vec<crate::models::CodeInterpreterToolOutput>,
  /// The status of the code interpreter tool call.
  #[serde(rename = "status")]
  status: String,
  /// The type of the code interpreter tool call. Always `code_interpreter_call`.
  #[serde(rename = "type")]
  _type: String
}
