/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CodeInterpreterFileOutputFiles {
  /// The ID of the file.
  #[serde(rename = "file_id")]
  file_id: String,
  /// The MIME type of the file.
  #[serde(rename = "mime_type")]
  mime_type: String
}
