/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CompletionUsage : Usage statistics for the completion request.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CompletionUsage {
  /// Number of tokens in the generated completion.
  #[serde(rename = "completion_tokens")]
  completion_tokens: i32,
  #[serde(rename = "completion_tokens_details")]
  completion_tokens_details: Option<crate::models::CompletionUsageCompletionTokensDetails>,
  /// Number of tokens in the prompt.
  #[serde(rename = "prompt_tokens")]
  prompt_tokens: i32,
  #[serde(rename = "prompt_tokens_details")]
  prompt_tokens_details: Option<crate::models::CompletionUsagePromptTokensDetails>,
  /// Total number of tokens used in the request (prompt + completion).
  #[serde(rename = "total_tokens")]
  total_tokens: i32
}
