/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ComputerCallSafetyCheckParam : A pending safety check for the computer call.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ComputerCallSafetyCheckParam {
  #[serde(rename = "code")]
  code: Option<Value>,
  /// The ID of the pending safety check.
  #[serde(rename = "id")]
  id: String,
  #[serde(rename = "message")]
  message: Option<Value>
}
