/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CompoundFilter : Combine multiple filters using `and` or `or`.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CompoundFilter {
  /// Array of filters to combine. Items can be `ComparisonFilter` or `CompoundFilter`.
  #[serde(rename = "filters")]
  filters: Vec<Value>,
  /// Type of operation: `and` or `or`.
  #[serde(rename = "type")]
  _type: String
}
