/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Coordinate : An x/y coordinate pair, e.g. `{ x: 100, y: 200 }`.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Coordinate {
  /// The x-coordinate.
  #[serde(rename = "x")]
  x: i32,
  /// The y-coordinate.
  #[serde(rename = "y")]
  y: i32
}
