/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CreateThreadRequest : Options to create a new thread. If no thread is provided when running a  request, an empty thread will be created.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateThreadRequest {
  /// A list of [messages](/docs/api-reference/messages) to start the thread with.
  #[serde(rename = "messages")]
  messages: Option<Vec<crate::models::CreateMessageRequest>>,
  #[serde(rename = "metadata")]
  metadata: Option<crate::models::Metadata>,
  #[serde(rename = "tool_resources")]
  tool_resources: Option<crate::models::CreateThreadRequestToolResources>
}
