/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateMessageRequestAttachments {
  /// The ID of the file to attach to the message.
  #[serde(rename = "file_id")]
  file_id: Option<String>,
  /// The tools to add this file to.
  #[serde(rename = "tools")]
  tools: Option<Vec<Value>>
}
