/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CreateModerationResponseCategoryScores : A list of the categories along with their scores as predicted by model.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateModerationResponseCategoryScores {
  /// The score for the category 'harassment'.
  #[serde(rename = "harassment")]
  harassment: f32,
  /// The score for the category 'harassment/threatening'.
  #[serde(rename = "harassment/threatening")]
  harassmentthreatening: f32,
  /// The score for the category 'hate'.
  #[serde(rename = "hate")]
  hate: f32,
  /// The score for the category 'hate/threatening'.
  #[serde(rename = "hate/threatening")]
  hatethreatening: f32,
  /// The score for the category 'illicit'.
  #[serde(rename = "illicit")]
  illicit: f32,
  /// The score for the category 'illicit/violent'.
  #[serde(rename = "illicit/violent")]
  illicitviolent: f32,
  /// The score for the category 'self-harm'.
  #[serde(rename = "self-harm")]
  self_harm: f32,
  /// The score for the category 'self-harm/instructions'.
  #[serde(rename = "self-harm/instructions")]
  self_harminstructions: f32,
  /// The score for the category 'self-harm/intent'.
  #[serde(rename = "self-harm/intent")]
  self_harmintent: f32,
  /// The score for the category 'sexual'.
  #[serde(rename = "sexual")]
  sexual: f32,
  /// The score for the category 'sexual/minors'.
  #[serde(rename = "sexual/minors")]
  sexualminors: f32,
  /// The score for the category 'violence'.
  #[serde(rename = "violence")]
  violence: f32,
  /// The score for the category 'violence/graphic'.
  #[serde(rename = "violence/graphic")]
  violencegraphic: f32
}
