/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateVectorStoreRequest {
  /// The chunking strategy used to chunk the file(s). If not set, will use the `auto` strategy. Only applicable if `file_ids` is non-empty.
  #[serde(rename = "chunking_strategy")]
  chunking_strategy: Option<Value>,
  #[serde(rename = "expires_after")]
  expires_after: Option<crate::models::VectorStoreExpirationAfter>,
  /// A list of [File](/docs/api-reference/files) IDs that the vector store should use. Useful for tools like `file_search` that can access files.
  #[serde(rename = "file_ids")]
  file_ids: Option<Vec<String>>,
  #[serde(rename = "metadata")]
  metadata: Option<crate::models::Metadata>,
  /// The name of the vector store.
  #[serde(rename = "name")]
  name: Option<String>
}
