/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CreateEmbeddingResponseUsage : The usage information for the request.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateEmbeddingResponseUsage {
  /// The number of tokens used by the prompt.
  #[serde(rename = "prompt_tokens")]
  prompt_tokens: i32,
  /// The total number of tokens used by the request.
  #[serde(rename = "total_tokens")]
  total_tokens: i32
}
