/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateCompletionResponseLogprobs {
  #[serde(rename = "text_offset")]
  text_offset: Option<Vec<i32>>,
  #[serde(rename = "token_logprobs")]
  token_logprobs: Option<Vec<f32>>,
  #[serde(rename = "tokens")]
  tokens: Option<Vec<String>>,
  #[serde(rename = "top_logprobs")]
  top_logprobs: Option<Vec<::std::collections::HashMap<String, f32>>>
}
