/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CreateModerationResponseCategoryAppliedInputTypes : A list of the categories along with the input type(s) that the score applies to.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateModerationResponseCategoryAppliedInputTypes {
  /// The applied input type(s) for the category 'harassment'.
  #[serde(rename = "harassment")]
  harassment: Vec<String>,
  /// The applied input type(s) for the category 'harassment/threatening'.
  #[serde(rename = "harassment/threatening")]
  harassmentthreatening: Vec<String>,
  /// The applied input type(s) for the category 'hate'.
  #[serde(rename = "hate")]
  hate: Vec<String>,
  /// The applied input type(s) for the category 'hate/threatening'.
  #[serde(rename = "hate/threatening")]
  hatethreatening: Vec<String>,
  /// The applied input type(s) for the category 'illicit'.
  #[serde(rename = "illicit")]
  illicit: Vec<String>,
  /// The applied input type(s) for the category 'illicit/violent'.
  #[serde(rename = "illicit/violent")]
  illicitviolent: Vec<String>,
  /// The applied input type(s) for the category 'self-harm'.
  #[serde(rename = "self-harm")]
  self_harm: Vec<String>,
  /// The applied input type(s) for the category 'self-harm/instructions'.
  #[serde(rename = "self-harm/instructions")]
  self_harminstructions: Vec<String>,
  /// The applied input type(s) for the category 'self-harm/intent'.
  #[serde(rename = "self-harm/intent")]
  self_harmintent: Vec<String>,
  /// The applied input type(s) for the category 'sexual'.
  #[serde(rename = "sexual")]
  sexual: Vec<String>,
  /// The applied input type(s) for the category 'sexual/minors'.
  #[serde(rename = "sexual/minors")]
  sexualminors: Vec<String>,
  /// The applied input type(s) for the category 'violence'.
  #[serde(rename = "violence")]
  violence: Vec<String>,
  /// The applied input type(s) for the category 'violence/graphic'.
  #[serde(rename = "violence/graphic")]
  violencegraphic: Vec<String>
}
