/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CreateModerationResponse : Represents if a given text input is potentially harmful.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateModerationResponse {
  /// The unique identifier for the moderation request.
  #[serde(rename = "id")]
  id: String,
  /// The model used to generate the moderation results.
  #[serde(rename = "model")]
  model: String,
  /// A list of moderation objects.
  #[serde(rename = "results")]
  results: Vec<crate::models::CreateModerationResponseResults>
}
