/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateTranscriptionResponseJsonLogprobs {
  /// The bytes of the token.
  #[serde(rename = "bytes")]
  bytes: Option<Vec<f32>>,
  /// The log probability of the token.
  #[serde(rename = "logprob")]
  logprob: Option<f32>,
  /// The token in the transcription.
  #[serde(rename = "token")]
  token: Option<String>
}
