/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeleteCertificateResponse {
  /// The ID of the certificate that was deleted.
  #[serde(rename = "id")]
  id: String,
  /// The object type, must be `certificate.deleted`.
  #[serde(rename = "object")]
  object: String
}
