/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeleteFineTuningCheckpointPermissionResponse {
  /// Whether the fine-tuned model checkpoint permission was successfully deleted.
  #[serde(rename = "deleted")]
  deleted: bool,
  /// The ID of the fine-tuned model checkpoint permission that was deleted.
  #[serde(rename = "id")]
  id: String,
  /// The object type, which is always \"checkpoint.permission\".
  #[serde(rename = "object")]
  object: String
}
