/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// EasyInputMessage : A message input to the model with a role indicating instruction following hierarchy. Instructions given with the `developer` or `system` role take precedence over instructions given with the `user` role. Messages with the `assistant` role are presumed to have been generated by the model in previous interactions.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct EasyInputMessage {
  /// Text, image, or audio input to the model, used to generate a response. Can also contain previous assistant responses.
  #[serde(rename = "content")]
  content: Value,
  /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`.
  #[serde(rename = "role")]
  role: String,
  /// The type of the message input. Always `message`.
  #[serde(rename = "type")]
  _type: Option<String>
}
