/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FilePath : A path to a file.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FilePath {
  /// The ID of the file.
  #[serde(rename = "file_id")]
  file_id: String,
  /// The index of the file in the list of files.
  #[serde(rename = "index")]
  index: i32,
  /// The type of the file path. Always `file_path`.
  #[serde(rename = "type")]
  _type: String
}
