/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTuneSupervisedMethod : Configuration for the supervised fine-tuning method.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuneSupervisedMethod {
  #[serde(rename = "hyperparameters")]
  hyperparameters: Option<crate::models::FineTuneSupervisedMethodHyperparameters>
}
