/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTunePreferenceRequestInputInput {
  #[serde(rename = "messages")]
  messages: Option<Vec<Value>>,
  #[serde(rename = "parallel_tool_calls")]
  parallel_tool_calls: Option<crate::models::ParallelToolCalls>,
  /// A list of tools the model may generate JSON inputs for.
  #[serde(rename = "tools")]
  tools: Option<Vec<crate::models::ChatCompletionTool>>
}
