/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTuneDpoMethod : Configuration for the DPO fine-tuning method.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuneDpoMethod {
  #[serde(rename = "hyperparameters")]
  hyperparameters: Option<crate::models::FineTuneDpoMethodHyperparameters>
}
