/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTuningJobError : For fine-tuning jobs that have `failed`, this will contain more information on the cause of the failure.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuningJobError {
  /// A machine-readable error code.
  #[serde(rename = "code")]
  code: String,
  /// A human-readable error message.
  #[serde(rename = "message")]
  message: String,
  /// The parameter that was invalid, usually `training_file` or `validation_file`. This field will be null if the failure was not parameter-specific.
  #[serde(rename = "param")]
  param: String
}
