/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTunePreferenceRequestInput : The per-line training example of a fine-tuning input file for chat models using the dpo method.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTunePreferenceRequestInput {
  #[serde(rename = "input")]
  input: Option<crate::models::FineTunePreferenceRequestInputInput>,
  /// The non-preferred completion message for the output.
  #[serde(rename = "non_preferred_completion")]
  non_preferred_completion: Option<Vec<Value>>,
  /// The preferred completion message for the output.
  #[serde(rename = "preferred_completion")]
  preferred_completion: Option<Vec<Value>>
}
