/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTuningJobCheckpoint : The `fine_tuning.job.checkpoint` object represents a model checkpoint for a fine-tuning job that is ready to use.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuningJobCheckpoint {
  /// The Unix timestamp (in seconds) for when the checkpoint was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The name of the fine-tuned checkpoint model that is created.
  #[serde(rename = "fine_tuned_model_checkpoint")]
  fine_tuned_model_checkpoint: String,
  /// The name of the fine-tuning job that this checkpoint was created from.
  #[serde(rename = "fine_tuning_job_id")]
  fine_tuning_job_id: String,
  /// The checkpoint identifier, which can be referenced in the API endpoints.
  #[serde(rename = "id")]
  id: String,
  #[serde(rename = "metrics")]
  metrics: crate::models::FineTuningJobCheckpointMetrics,
  /// The object type, which is always \"fine_tuning.job.checkpoint\".
  #[serde(rename = "object")]
  object: String,
  /// The step number that the checkpoint was created at.
  #[serde(rename = "step_number")]
  step_number: i32
}
