/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTuningJobCheckpointMetrics : Metrics at the step number during the fine-tuning job.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuningJobCheckpointMetrics {
  #[serde(rename = "full_valid_loss")]
  full_valid_loss: Option<f32>,
  #[serde(rename = "full_valid_mean_token_accuracy")]
  full_valid_mean_token_accuracy: Option<f32>,
  #[serde(rename = "step")]
  step: Option<f32>,
  #[serde(rename = "train_loss")]
  train_loss: Option<f32>,
  #[serde(rename = "train_mean_token_accuracy")]
  train_mean_token_accuracy: Option<f32>,
  #[serde(rename = "valid_loss")]
  valid_loss: Option<f32>,
  #[serde(rename = "valid_mean_token_accuracy")]
  valid_mean_token_accuracy: Option<f32>
}
