/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuneChatCompletionRequestAssistantMessage {
  #[serde(rename = "audio")]
  audio: Option<crate::models::ChatCompletionRequestAssistantMessageAudio>,
  /// The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
  #[serde(rename = "content")]
  content: Option<Value>,
  #[serde(rename = "function_call")]
  function_call: Option<crate::models::ChatCompletionRequestAssistantMessageFunctionCall>,
  /// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
  #[serde(rename = "name")]
  name: Option<String>,
  /// The refusal message by the assistant.
  #[serde(rename = "refusal")]
  refusal: Option<String>,
  /// The role of the messages author, in this case `assistant`.
  #[serde(rename = "role")]
  role: String,
  #[serde(rename = "tool_calls")]
  tool_calls: Option<crate::models::ChatCompletionMessageToolCalls>
}
