/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTuningCheckpointPermission : The `checkpoint.permission` object represents a permission for a fine-tuned model checkpoint.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuningCheckpointPermission {
  /// The Unix timestamp (in seconds) for when the permission was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The permission identifier, which can be referenced in the API endpoints.
  #[serde(rename = "id")]
  id: String,
  /// The object type, which is always \"checkpoint.permission\".
  #[serde(rename = "object")]
  object: String,
  /// The project identifier that the permission is for.
  #[serde(rename = "project_id")]
  project_id: String
}
