/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTuningJobEvent : Fine-tuning job event object

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuningJobEvent {
  /// The Unix timestamp (in seconds) for when the fine-tuning job was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The data associated with the event.
  #[serde(rename = "data")]
  data: Option<Value>,
  /// The object identifier.
  #[serde(rename = "id")]
  id: String,
  /// The log level of the event.
  #[serde(rename = "level")]
  level: String,
  /// The message of the event.
  #[serde(rename = "message")]
  message: String,
  /// The object type, which is always \"fine_tuning.job.event\".
  #[serde(rename = "object")]
  object: String,
  /// The type of event.
  #[serde(rename = "type")]
  _type: Option<String>
}
