/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FineTuneMethod : The method used for fine-tuning.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FineTuneMethod {
  #[serde(rename = "dpo")]
  dpo: Option<crate::models::FineTuneDpoMethod>,
  #[serde(rename = "supervised")]
  supervised: Option<crate::models::FineTuneSupervisedMethod>,
  /// The type of method. Is either `supervised` or `dpo`.
  #[serde(rename = "type")]
  _type: Option<String>
}
