/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FunctionToolCallOutputResource {
  /// The unique ID of the function tool call generated by the model.
  #[serde(rename = "call_id")]
  call_id: String,
  /// The unique ID of the function call tool output.
  #[serde(rename = "id")]
  id: String,
  /// A JSON string of the output of the function tool call.
  #[serde(rename = "output")]
  output: String,
  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
  #[serde(rename = "status")]
  status: Option<String>,
  /// The type of the function tool call output. Always `function_call_output`.
  #[serde(rename = "type")]
  _type: String
}
