/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FunctionToolCall : A tool call to run a function. See the  [function calling guide](/docs/guides/function-calling) for more information.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FunctionToolCall {
  /// A JSON string of the arguments to pass to the function.
  #[serde(rename = "arguments")]
  arguments: String,
  /// The unique ID of the function tool call generated by the model.
  #[serde(rename = "call_id")]
  call_id: String,
  /// The unique ID of the function tool call.
  #[serde(rename = "id")]
  id: Option<String>,
  /// The name of the function to run.
  #[serde(rename = "name")]
  name: String,
  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
  #[serde(rename = "status")]
  status: Option<String>,
  /// The type of the function tool call. Always `function_call`.
  #[serde(rename = "type")]
  _type: String
}
