/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FunctionTool : Defines a function in your own code the model can choose to call. Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FunctionTool {
  #[serde(rename = "parameters")]
  parameters: Value,
  #[serde(rename = "description")]
  description: Option<Value>,
  /// The name of the function to call.
  #[serde(rename = "name")]
  name: String,
  #[serde(rename = "strict")]
  strict: Value,
  /// The type of the function tool. Always `function`.
  #[serde(rename = "type")]
  _type: String
}
