/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ImagesResponse : The response from the image generation endpoint.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ImagesResponse {
  /// The Unix timestamp (in seconds) of when the image was created.
  #[serde(rename = "created")]
  created: i32,
  /// The list of generated images.
  #[serde(rename = "data")]
  data: Option<Vec<crate::models::Image>>,
  #[serde(rename = "usage")]
  usage: Option<crate::models::ImagesResponseUsage>
}
