/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ImagesResponseUsage : For `gpt-image-1` only, the token usage information for the image generation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ImagesResponseUsage {
  /// The number of tokens (images and text) in the input prompt.
  #[serde(rename = "input_tokens")]
  input_tokens: i32,
  #[serde(rename = "input_tokens_details")]
  input_tokens_details: crate::models::ImagesResponseUsageInputTokensDetails,
  /// The number of image tokens in the output image.
  #[serde(rename = "output_tokens")]
  output_tokens: i32,
  /// The total number of tokens (images and text) used for the image generation.
  #[serde(rename = "total_tokens")]
  total_tokens: i32
}
