/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ImagesResponseUsageInputTokensDetails : The input tokens detailed information for the image generation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ImagesResponseUsageInputTokensDetails {
  /// The number of image tokens in the input prompt.
  #[serde(rename = "image_tokens")]
  image_tokens: i32,
  /// The number of text tokens in the input prompt.
  #[serde(rename = "text_tokens")]
  text_tokens: i32
}
