/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// InputImageContent : An image input to the model. Learn about [image inputs](/docs/guides/vision).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InputImageContent {
  /// The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`.
  #[serde(rename = "detail")]
  detail: String,
  #[serde(rename = "file_id")]
  file_id: Option<Value>,
  #[serde(rename = "image_url")]
  image_url: Option<Value>,
  /// The type of the input item. Always `input_image`.
  #[serde(rename = "type")]
  _type: String
}
