/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// InputFileContent : A file input to the model.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InputFileContent {
  /// The content of the file to be sent to the model.
  #[serde(rename = "file_data")]
  file_data: Option<String>,
  #[serde(rename = "file_id")]
  file_id: Option<Value>,
  /// The name of the file to be sent to the model.
  #[serde(rename = "filename")]
  filename: Option<String>,
  /// The type of the input item. Always `input_file`.
  #[serde(rename = "type")]
  _type: String
}
