/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InviteListResponse {
  #[serde(rename = "data")]
  data: Vec<crate::models::Invite>,
  /// The first `invite_id` in the retrieved `list`
  #[serde(rename = "first_id")]
  first_id: Option<String>,
  /// The `has_more` property is used for pagination to indicate there are additional results.
  #[serde(rename = "has_more")]
  has_more: Option<bool>,
  /// The last `invite_id` in the retrieved `list`
  #[serde(rename = "last_id")]
  last_id: Option<String>,
  /// The object type, which is always `list`
  #[serde(rename = "object")]
  object: String
}
