/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Invite : Represents an individual `invite` to the organization.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Invite {
  /// The Unix timestamp (in seconds) of when the invite was accepted.
  #[serde(rename = "accepted_at")]
  accepted_at: Option<i32>,
  /// The email address of the individual to whom the invite was sent
  #[serde(rename = "email")]
  email: String,
  /// The Unix timestamp (in seconds) of when the invite expires.
  #[serde(rename = "expires_at")]
  expires_at: i32,
  /// The identifier, which can be referenced in API endpoints
  #[serde(rename = "id")]
  id: String,
  /// The Unix timestamp (in seconds) of when the invite was sent.
  #[serde(rename = "invited_at")]
  invited_at: i32,
  /// The object type, which is always `organization.invite`
  #[serde(rename = "object")]
  object: String,
  /// The projects that were granted membership upon acceptance of the invite.
  #[serde(rename = "projects")]
  projects: Option<Vec<crate::models::InviteProjects>>,
  /// `owner` or `reader`
  #[serde(rename = "role")]
  role: String,
  /// `accepted`,`expired`, or `pending`
  #[serde(rename = "status")]
  status: String
}
