/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ItemReferenceParam : An internal identifier for an item to reference.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ItemReferenceParam {
  /// The ID of the item to reference.
  #[serde(rename = "id")]
  id: String,
  #[serde(rename = "type")]
  _type: Option<Value>
}
