/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// KeyPress : A collection of keypresses the model would like to perform.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct KeyPress {
  /// The combination of keys the model is requesting to be pressed. This is an array of strings, each representing a key.
  #[serde(rename = "keys")]
  keys: Vec<String>,
  /// Specifies the event type. For a keypress action, this property is  always set to `keypress`.
  #[serde(rename = "type")]
  _type: String
}
