/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ListRunsResponse {
  #[serde(rename = "data")]
  data: Vec<crate::models::RunObject>,
  #[serde(rename = "first_id")]
  first_id: String,
  #[serde(rename = "has_more")]
  has_more: bool,
  #[serde(rename = "last_id")]
  last_id: String,
  #[serde(rename = "object")]
  object: String
}
