/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MessageDeltaContentTextObject : The text content that is part of a message.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageDeltaContentTextObject {
  /// The index of the content part in the message.
  #[serde(rename = "index")]
  index: i32,
  #[serde(rename = "text")]
  text: Option<crate::models::MessageDeltaContentTextObjectText>,
  /// Always `text`.
  #[serde(rename = "type")]
  _type: String
}
