/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MessageDeltaContentRefusalObject : The refusal content that is part of a message.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageDeltaContentRefusalObject {
  /// The index of the refusal part in the message.
  #[serde(rename = "index")]
  index: i32,
  #[serde(rename = "refusal")]
  refusal: Option<String>,
  /// Always `refusal`.
  #[serde(rename = "type")]
  _type: String
}
