/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MessageRequestContentTextObject : The text content that is part of a message.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageRequestContentTextObject {
  /// Text content to be sent to the model
  #[serde(rename = "text")]
  text: String,
  /// Always `text`.
  #[serde(rename = "type")]
  _type: String
}
