/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MessageDeltaContentImageFileObject : References an image [File](/docs/api-reference/files) in the content of a message.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageDeltaContentImageFileObject {
  #[serde(rename = "image_file")]
  image_file: Option<crate::models::MessageDeltaContentImageFileObjectImageFile>,
  /// The index of the content part in the message.
  #[serde(rename = "index")]
  index: i32,
  /// Always `image_file`.
  #[serde(rename = "type")]
  _type: String
}
