/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MessageDeltaContentImageUrlObject : References an image URL in the content of a message.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageDeltaContentImageUrlObject {
  #[serde(rename = "image_url")]
  image_url: Option<crate::models::MessageDeltaContentImageUrlObjectImageUrl>,
  /// The index of the content part in the message.
  #[serde(rename = "index")]
  index: i32,
  /// Always `image_url`.
  #[serde(rename = "type")]
  _type: String
}
