/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MessageContentRefusalObject : The refusal content generated by the assistant.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageContentRefusalObject {
  #[serde(rename = "refusal")]
  refusal: String,
  /// Always `refusal`.
  #[serde(rename = "type")]
  _type: String
}
