/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MessageContentImageUrlObject : References an image URL in the content of a message.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageContentImageUrlObject {
  #[serde(rename = "image_url")]
  image_url: crate::models::MessageContentImageUrlObjectImageUrl,
  /// The type of the content part.
  #[serde(rename = "type")]
  _type: String
}
