/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ModelMove : A mouse move action.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelMove {
  /// Specifies the event type. For a move action, this property is  always set to `move`.
  #[serde(rename = "type")]
  _type: String,
  /// The x-coordinate to move to.
  #[serde(rename = "x")]
  x: i32,
  /// The y-coordinate to move to.
  #[serde(rename = "y")]
  y: i32
}
