/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ModelType : An action to type in text.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelType {
  /// The text to type.
  #[serde(rename = "text")]
  text: String,
  /// Specifies the event type. For a type action, this property is  always set to `type`.
  #[serde(rename = "type")]
  _type: String
}
