/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModifyThreadRequest {
  #[serde(rename = "metadata")]
  metadata: Option<crate::models::Metadata>,
  #[serde(rename = "tool_resources")]
  tool_resources: Option<crate::models::ModifyThreadRequestToolResources>
}
