/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// OpenAiFile : The `File` object represents a document that has been uploaded to OpenAI.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct OpenAiFile {
  /// The size of the file, in bytes.
  #[serde(rename = "bytes")]
  bytes: i32,
  /// The Unix timestamp (in seconds) for when the file was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The Unix timestamp (in seconds) for when the file will expire.
  #[serde(rename = "expires_at")]
  expires_at: Option<i32>,
  /// The name of the file.
  #[serde(rename = "filename")]
  filename: String,
  /// The file identifier, which can be referenced in the API endpoints.
  #[serde(rename = "id")]
  id: String,
  /// The object type, which is always `file`.
  #[serde(rename = "object")]
  object: String,
  /// The intended purpose of the file. Supported values are `assistants`, `assistants_output`, `batch`, `batch_output`, `fine-tune`, `fine-tune-results` and `vision`.
  #[serde(rename = "purpose")]
  purpose: String,
  /// Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or `error`.
  #[serde(rename = "status")]
  status: String,
  /// Deprecated. For details on why a fine-tuning training file failed validation, see the `error` field on `fine_tuning.job`.
  #[serde(rename = "status_details")]
  status_details: Option<String>
}
