/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// OutputTextContent : A text output from the model.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct OutputTextContent {
  /// The annotations of the text output.
  #[serde(rename = "annotations")]
  annotations: Vec<crate::models::Annotation>,
  /// The text output from the model.
  #[serde(rename = "text")]
  text: String,
  /// The type of the output text. Always `output_text`.
  #[serde(rename = "type")]
  _type: String
}
