/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// OutputMessage : An output message from the model.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct OutputMessage {
  /// The content of the output message.
  #[serde(rename = "content")]
  content: Vec<crate::models::OutputContent>,
  /// The unique ID of the output message.
  #[serde(rename = "id")]
  id: String,
  /// The role of the output message. Always `assistant`.
  #[serde(rename = "role")]
  role: String,
  /// The status of the message input. One of `in_progress`, `completed`, or `incomplete`. Populated when input items are returned via API.
  #[serde(rename = "status")]
  status: String,
  /// The type of the output message. Always `message`.
  #[serde(rename = "type")]
  _type: String
}
