/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ProjectApiKey : Represents an individual API key in a project.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ProjectApiKey {
  /// The Unix timestamp (in seconds) of when the API key was created
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The identifier, which can be referenced in API endpoints
  #[serde(rename = "id")]
  id: String,
  /// The Unix timestamp (in seconds) of when the API key was last used.
  #[serde(rename = "last_used_at")]
  last_used_at: i32,
  /// The name of the API key
  #[serde(rename = "name")]
  name: String,
  /// The object type, which is always `organization.project.api_key`
  #[serde(rename = "object")]
  object: String,
  #[serde(rename = "owner")]
  owner: crate::models::ProjectApiKeyOwner,
  /// The redacted value of the API key
  #[serde(rename = "redacted_value")]
  redacted_value: String
}
