/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ProjectServiceAccountApiKey {
  #[serde(rename = "created_at")]
  created_at: i32,
  #[serde(rename = "id")]
  id: String,
  #[serde(rename = "name")]
  name: String,
  /// The object type, which is always `organization.project.service_account.api_key`
  #[serde(rename = "object")]
  object: String,
  #[serde(rename = "value")]
  value: String
}
