/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Project : Represents an individual project.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Project {
  /// The Unix timestamp (in seconds) of when the project was archived or `null`.
  #[serde(rename = "archived_at")]
  archived_at: Option<i32>,
  /// The Unix timestamp (in seconds) of when the project was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The identifier, which can be referenced in API endpoints
  #[serde(rename = "id")]
  id: String,
  /// The name of the project. This appears in reporting.
  #[serde(rename = "name")]
  name: String,
  /// The object type, which is always `organization.project`
  #[serde(rename = "object")]
  object: String,
  /// `active` or `archived`
  #[serde(rename = "status")]
  status: String
}
