/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ProjectApiKeyOwner {
  #[serde(rename = "service_account")]
  service_account: Option<crate::models::ProjectServiceAccount>,
  /// `user` or `service_account`
  #[serde(rename = "type")]
  _type: Option<String>,
  #[serde(rename = "user")]
  user: Option<crate::models::ProjectUser>
}
