/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventConversationItemInputAudioTranscriptionDelta : Returned when the text value of an input audio transcription content part is updated.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventConversationItemInputAudioTranscriptionDelta {
  /// The index of the content part in the item's content array.
  #[serde(rename = "content_index")]
  content_index: Option<i32>,
  /// The text delta.
  #[serde(rename = "delta")]
  delta: Option<String>,
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  /// The ID of the item.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The log probabilities of the transcription.
  #[serde(rename = "logprobs")]
  logprobs: Option<Vec<crate::models::LogProbProperties>>,
  /// The event type, must be `conversation.item.input_audio_transcription.delta`.
  #[serde(rename = "type")]
  _type: String
}
