/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeSessionCreateResponseTurnDetection : Configuration for turn detection. Can be set to `null` to turn off. Server  VAD means that the model will detect the start and end of speech based on  audio volume and respond at the end of user speech.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeSessionCreateResponseTurnDetection {
  /// Amount of audio to include before the VAD detected speech (in  milliseconds). Defaults to 300ms.
  #[serde(rename = "prefix_padding_ms")]
  prefix_padding_ms: Option<i32>,
  /// Duration of silence to detect speech stop (in milliseconds). Defaults  to 500ms. With shorter values the model will respond more quickly,  but may jump in on short pauses from the user.
  #[serde(rename = "silence_duration_ms")]
  silence_duration_ms: Option<i32>,
  /// Activation threshold for VAD (0.0 to 1.0), this defaults to 0.5. A  higher threshold will require louder audio to activate the model, and  thus might perform better in noisy environments.
  #[serde(rename = "threshold")]
  threshold: Option<f32>,
  /// Type of turn detection, only `server_vad` is currently supported.
  #[serde(rename = "type")]
  _type: Option<String>
}
