/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeClientEventTranscriptionSessionUpdate : Send this event to update a transcription session.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeClientEventTranscriptionSessionUpdate {
  /// Optional client-generated ID used to identify this event.
  #[serde(rename = "event_id")]
  event_id: Option<String>,
  #[serde(rename = "session")]
  session: crate::models::RealtimeTranscriptionSessionCreateRequest,
  /// The event type, must be `transcription_session.update`.
  #[serde(rename = "type")]
  _type: String
}
