/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventErrorError : Details of the error.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventErrorError {
  /// Error code, if any.
  #[serde(rename = "code")]
  code: Option<String>,
  /// The event_id of the client event that caused the error, if applicable.
  #[serde(rename = "event_id")]
  event_id: Option<String>,
  /// A human-readable error message.
  #[serde(rename = "message")]
  message: String,
  /// Parameter related to the error, if any.
  #[serde(rename = "param")]
  param: Option<String>,
  /// The type of error (e.g., \"invalid_request_error\", \"server_error\").
  #[serde(rename = "type")]
  _type: String
}
