/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventConversationItemInputAudioTranscriptionFailedError : Details of the transcription error.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventConversationItemInputAudioTranscriptionFailedError {
  /// Error code, if any.
  #[serde(rename = "code")]
  code: Option<String>,
  /// A human-readable error message.
  #[serde(rename = "message")]
  message: Option<String>,
  /// Parameter related to the error, if any.
  #[serde(rename = "param")]
  param: Option<String>,
  /// The type of error.
  #[serde(rename = "type")]
  _type: Option<String>
}
