/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventConversationCreated : Returned when a conversation is created. Emitted right after session creation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventConversationCreated {
  #[serde(rename = "conversation")]
  conversation: crate::models::RealtimeServerEventConversationCreatedConversation,
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  /// The event type, must be `conversation.created`.
  #[serde(rename = "type")]
  _type: String
}
