/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventResponseOutputItemDone : Returned when an Item is done streaming. Also emitted when a Response is  interrupted, incomplete, or cancelled.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventResponseOutputItemDone {
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  #[serde(rename = "item")]
  item: crate::models::RealtimeConversationItem,
  /// The index of the output item in the Response.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The ID of the Response to which the item belongs.
  #[serde(rename = "response_id")]
  response_id: String,
  /// The event type, must be `response.output_item.done`.
  #[serde(rename = "type")]
  _type: String
}
