/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventError : Returned when an error occurs, which could be a client problem or a server  problem. Most errors are recoverable and the session will stay open, we  recommend to implementors to monitor and log error messages by default.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventError {
  #[serde(rename = "error")]
  error: crate::models::RealtimeServerEventErrorError,
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  /// The event type, must be `error`.
  #[serde(rename = "type")]
  _type: String
}
