/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeResponseUsageInputTokenDetails : Details about the input tokens used in the Response.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeResponseUsageInputTokenDetails {
  /// The number of audio tokens used in the Response.
  #[serde(rename = "audio_tokens")]
  audio_tokens: Option<i32>,
  /// The number of cached tokens used in the Response.
  #[serde(rename = "cached_tokens")]
  cached_tokens: Option<i32>,
  /// The number of text tokens used in the Response.
  #[serde(rename = "text_tokens")]
  text_tokens: Option<i32>
}
