/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventResponseAudioDelta : Returned when the model-generated audio is updated.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventResponseAudioDelta {
  /// The index of the content part in the item's content array.
  #[serde(rename = "content_index")]
  content_index: i32,
  /// Base64-encoded audio data delta.
  #[serde(rename = "delta")]
  delta: String,
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  /// The ID of the item.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item in the response.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The ID of the response.
  #[serde(rename = "response_id")]
  response_id: String,
  /// The event type, must be `response.audio.delta`.
  #[serde(rename = "type")]
  _type: String
}
