/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventResponseContentPartDone : Returned when a content part is done streaming in an assistant message item. Also emitted when a Response is interrupted, incomplete, or cancelled.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventResponseContentPartDone {
  /// The index of the content part in the item's content array.
  #[serde(rename = "content_index")]
  content_index: i32,
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  /// The ID of the item.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item in the response.
  #[serde(rename = "output_index")]
  output_index: i32,
  #[serde(rename = "part")]
  part: crate::models::RealtimeServerEventResponseContentPartDonePart,
  /// The ID of the response.
  #[serde(rename = "response_id")]
  response_id: String,
  /// The event type, must be `response.content_part.done`.
  #[serde(rename = "type")]
  _type: String
}
