/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventResponseContentPartDonePart : The content part that is done.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventResponseContentPartDonePart {
  /// Base64-encoded audio data (if type is \"audio\").
  #[serde(rename = "audio")]
  audio: Option<String>,
  /// The text content (if type is \"text\").
  #[serde(rename = "text")]
  text: Option<String>,
  /// The transcript of the audio (if type is \"audio\").
  #[serde(rename = "transcript")]
  transcript: Option<String>,
  /// The content type (\"text\", \"audio\").
  #[serde(rename = "type")]
  _type: Option<String>
}
