/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventInputAudioBufferCleared : Returned when the input audio buffer is cleared by the client with a  `input_audio_buffer.clear` event.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventInputAudioBufferCleared {
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  /// The event type, must be `input_audio_buffer.cleared`.
  #[serde(rename = "type")]
  _type: String
}
