/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventResponseFunctionCallArgumentsDone : Returned when the model-generated function call arguments are done streaming. Also emitted when a Response is interrupted, incomplete, or cancelled.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventResponseFunctionCallArgumentsDone {
  /// The final arguments as a JSON string.
  #[serde(rename = "arguments")]
  arguments: String,
  /// The ID of the function call.
  #[serde(rename = "call_id")]
  call_id: String,
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  /// The ID of the function call item.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item in the response.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The ID of the response.
  #[serde(rename = "response_id")]
  response_id: String,
  /// The event type, must be `response.function_call_arguments.done`.
  #[serde(rename = "type")]
  _type: String
}
