/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventSessionCreated : Returned when a Session is created. Emitted automatically when a new  connection is established as the first server event. This event will contain  the default Session configuration.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventSessionCreated {
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  #[serde(rename = "session")]
  session: crate::models::RealtimeSession,
  /// The event type, must be `session.created`.
  #[serde(rename = "type")]
  _type: String
}
