/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RealtimeServerEventResponseCreated : Returned when a new Response is created. The first event of response creation, where the response is in an initial state of `in_progress`.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RealtimeServerEventResponseCreated {
  /// The unique ID of the server event.
  #[serde(rename = "event_id")]
  event_id: String,
  #[serde(rename = "response")]
  response: crate::models::RealtimeResponse,
  /// The event type, must be `response.created`.
  #[serde(rename = "type")]
  _type: String
}
