/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Reasoning : **o-series models only**  Configuration options for  [reasoning models](https://platform.openai.com/docs/guides/reasoning).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Reasoning {
  #[serde(rename = "effort")]
  effort: Option<crate::models::ReasoningEffort>,
  /// **Deprecated:** use `summary` instead.  A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. One of `auto`, `concise`, or `detailed`.
  #[serde(rename = "generate_summary")]
  generate_summary: Option<String>,
  /// A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. One of `auto`, `concise`, or `detailed`.
  #[serde(rename = "summary")]
  summary: Option<String>
}
