/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ReasoningItemSummary {
  /// A short summary of the reasoning used by the model when generating the response.
  #[serde(rename = "text")]
  text: String,
  /// The type of the object. Always `summary_text`.
  #[serde(rename = "type")]
  _type: String
}
