/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ReasoningItem : A description of the chain of thought used by a reasoning model while generating a response.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ReasoningItem {
  /// The unique identifier of the reasoning content.
  #[serde(rename = "id")]
  id: String,
  /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
  #[serde(rename = "status")]
  status: Option<String>,
  /// Reasoning text contents.
  #[serde(rename = "summary")]
  summary: Vec<crate::models::ReasoningItemSummary>,
  /// The type of the object. Always `reasoning`.
  #[serde(rename = "type")]
  _type: String
}
