/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RefusalContent : A refusal from the model.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RefusalContent {
  /// The refusal explanationfrom the model.
  #[serde(rename = "refusal")]
  refusal: String,
  /// The type of the refusal. Always `refusal`.
  #[serde(rename = "type")]
  _type: String
}
