/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseWebSearchCallCompletedEvent : Emitted when a web search call is completed.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseWebSearchCallCompletedEvent {
  /// Unique ID for the output item associated with the web search call.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item that the web search call is associated with.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The type of the event. Always `response.web_search_call.completed`.
  #[serde(rename = "type")]
  _type: String
}
