/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseAudioTranscriptDeltaEvent : Emitted when there is a partial transcript of audio.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseAudioTranscriptDeltaEvent {
  /// The partial transcript of the audio response.
  #[serde(rename = "delta")]
  delta: String,
  /// The type of the event. Always `response.audio.transcript.delta`.
  #[serde(rename = "type")]
  _type: String
}
