/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseInProgressEvent : Emitted when the response is in progress.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseInProgressEvent {
  /// The response that is in progress.
  #[serde(rename = "response")]
  response: crate::models::Response,
  /// The type of the event. Always `response.in_progress`.
  #[serde(rename = "type")]
  _type: String
}
