/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseContentPartAddedEvent : Emitted when a new content part is added.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseContentPartAddedEvent {
  /// The index of the content part that was added.
  #[serde(rename = "content_index")]
  content_index: i32,
  /// The ID of the output item that the content part was added to.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item that the content part was added to.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The content part that was added.
  #[serde(rename = "part")]
  part: crate::models::OutputContent,
  /// The type of the event. Always `response.content_part.added`.
  #[serde(rename = "type")]
  _type: String
}
