/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseItemList : A list of Response items.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseItemList {
  /// A list of items used to generate this response.
  #[serde(rename = "data")]
  data: Vec<crate::models::ItemResource>,
  /// The ID of the first item in the list.
  #[serde(rename = "first_id")]
  first_id: String,
  /// Whether there are more items available.
  #[serde(rename = "has_more")]
  has_more: bool,
  /// The ID of the last item in the list.
  #[serde(rename = "last_id")]
  last_id: String,
  /// The type of object returned, must be `list`.
  #[serde(rename = "object")]
  object: String
}
