/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseFunctionCallArgumentsDeltaEvent : Emitted when there is a partial function-call arguments delta.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseFunctionCallArgumentsDeltaEvent {
  /// The function-call arguments delta that is added.
  #[serde(rename = "delta")]
  delta: String,
  /// The ID of the output item that the function-call arguments delta is added to.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item that the function-call arguments delta is added to.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The type of the event. Always `response.function_call_arguments.delta`.
  #[serde(rename = "type")]
  _type: String
}
