/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseReasoningSummaryTextDeltaEvent : Emitted when a delta is added to a reasoning summary text.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseReasoningSummaryTextDeltaEvent {
  /// The text delta that was added to the summary.
  #[serde(rename = "delta")]
  delta: String,
  /// The ID of the item this summary text delta is associated with.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item this summary text delta is associated with.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The index of the summary part within the reasoning summary.
  #[serde(rename = "summary_index")]
  summary_index: i32,
  /// The type of the event. Always `response.reasoning_summary_text.delta`.
  #[serde(rename = "type")]
  _type: String
}
