/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseFileSearchCallInProgressEvent : Emitted when a file search call is initiated.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseFileSearchCallInProgressEvent {
  /// The ID of the output item that the file search call is initiated.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item that the file search call is initiated.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The type of the event. Always `response.file_search_call.in_progress`.
  #[serde(rename = "type")]
  _type: String
}
