/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseReasoningSummaryPartAddedEventPart : The summary part that was added.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseReasoningSummaryPartAddedEventPart {
  /// The text of the summary part.
  #[serde(rename = "text")]
  text: String,
  /// The type of the summary part. Always `summary_text`.
  #[serde(rename = "type")]
  _type: String
}
