/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseErrorEvent : Emitted when an error occurs.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseErrorEvent {
  /// The error code.
  #[serde(rename = "code")]
  code: String,
  /// The error message.
  #[serde(rename = "message")]
  message: String,
  /// The error parameter.
  #[serde(rename = "param")]
  param: String,
  /// The type of the event. Always `error`.
  #[serde(rename = "type")]
  _type: String
}
