/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseOutputItemAddedEvent : Emitted when a new output item is added.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseOutputItemAddedEvent {
  /// The output item that was added.
  #[serde(rename = "item")]
  item: crate::models::OutputItem,
  /// The index of the output item that was added.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The type of the event. Always `response.output_item.added`.
  #[serde(rename = "type")]
  _type: String
}
