/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseCompletedEvent : Emitted when the model response is complete.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseCompletedEvent {
  /// Properties of the completed response.
  #[serde(rename = "response")]
  response: crate::models::Response,
  /// The type of the event. Always `response.completed`.
  #[serde(rename = "type")]
  _type: String
}
