/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseError : An error object returned when the model fails to generate a Response.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseError {
  #[serde(rename = "code")]
  code: crate::models::ResponseErrorCode,
  /// A human-readable description of the error.
  #[serde(rename = "message")]
  message: String
}
