/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseAudioDeltaEvent : Emitted when there is a partial audio response.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseAudioDeltaEvent {
  /// A chunk of Base64 encoded response audio bytes.
  #[serde(rename = "delta")]
  delta: String,
  /// The type of the event. Always `response.audio.delta`.
  #[serde(rename = "type")]
  _type: String
}
