/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseRefusalDoneEvent : Emitted when refusal text is finalized.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseRefusalDoneEvent {
  /// The index of the content part that the refusal text is finalized.
  #[serde(rename = "content_index")]
  content_index: i32,
  /// The ID of the output item that the refusal text is finalized.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item that the refusal text is finalized.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The refusal text that is finalized.
  #[serde(rename = "refusal")]
  refusal: String,
  /// The type of the event. Always `response.refusal.done`.
  #[serde(rename = "type")]
  _type: String
}
