/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseTextDoneEvent : Emitted when text content is finalized.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseTextDoneEvent {
  /// The index of the content part that the text content is finalized.
  #[serde(rename = "content_index")]
  content_index: i32,
  /// The ID of the output item that the text content is finalized.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item that the text content is finalized.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The text content that is finalized.
  #[serde(rename = "text")]
  text: String,
  /// The type of the event. Always `response.output_text.done`.
  #[serde(rename = "type")]
  _type: String
}
