/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseUsage : Represents token usage details including input tokens, output tokens, a breakdown of output tokens, and the total tokens used.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseUsage {
  /// The number of input tokens.
  #[serde(rename = "input_tokens")]
  input_tokens: i32,
  #[serde(rename = "input_tokens_details")]
  input_tokens_details: crate::models::ResponseUsageInputTokensDetails,
  /// The number of output tokens.
  #[serde(rename = "output_tokens")]
  output_tokens: i32,
  #[serde(rename = "output_tokens_details")]
  output_tokens_details: crate::models::ResponseUsageOutputTokensDetails,
  /// The total number of tokens used.
  #[serde(rename = "total_tokens")]
  total_tokens: i32
}
