/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseTextDeltaEvent : Emitted when there is an additional text delta.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseTextDeltaEvent {
  /// The index of the content part that the text delta was added to.
  #[serde(rename = "content_index")]
  content_index: i32,
  /// The text delta that was added.
  #[serde(rename = "delta")]
  delta: String,
  /// The ID of the output item that the text delta was added to.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item that the text delta was added to.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The type of the event. Always `response.output_text.delta`.
  #[serde(rename = "type")]
  _type: String
}
