/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponseTextAnnotationDeltaEvent : Emitted when a text annotation is added.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponseTextAnnotationDeltaEvent {
  #[serde(rename = "annotation")]
  annotation: crate::models::Annotation,
  /// The index of the annotation that was added.
  #[serde(rename = "annotation_index")]
  annotation_index: i32,
  /// The index of the content part that the text annotation was added to.
  #[serde(rename = "content_index")]
  content_index: i32,
  /// The ID of the output item that the text annotation was added to.
  #[serde(rename = "item_id")]
  item_id: String,
  /// The index of the output item that the text annotation was added to.
  #[serde(rename = "output_index")]
  output_index: i32,
  /// The type of the event. Always `response.output_text.annotation.added`.
  #[serde(rename = "type")]
  _type: String
}
