/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunStepDeltaObject : Represents a run step delta i.e. any changed fields on a run step during streaming.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunStepDeltaObject {
  #[serde(rename = "delta")]
  delta: crate::models::RunStepDeltaObjectDelta,
  /// The identifier of the run step, which can be referenced in API endpoints.
  #[serde(rename = "id")]
  id: String,
  /// The object type, which is always `thread.run.step.delta`.
  #[serde(rename = "object")]
  object: String
}
