/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunStepDeltaStepDetailsToolCallsCodeObject : Details of the Code Interpreter tool call the run step was involved in.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunStepDeltaStepDetailsToolCallsCodeObject {
  #[serde(rename = "code_interpreter")]
  code_interpreter: Option<crate::models::RunStepDeltaStepDetailsToolCallsCodeObjectCodeInterpreter>,
  /// The ID of the tool call.
  #[serde(rename = "id")]
  id: Option<String>,
  /// The index of the tool call in the tool calls array.
  #[serde(rename = "index")]
  index: i32,
  /// The type of tool call. This is always going to be `code_interpreter` for this type of tool call.
  #[serde(rename = "type")]
  _type: String
}
