/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunCompletionUsage : Usage statistics related to the run. This value will be `null` if the run is not in a terminal state (i.e. `in_progress`, `queued`, etc.).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunCompletionUsage {
  /// Number of completion tokens used over the course of the run.
  #[serde(rename = "completion_tokens")]
  completion_tokens: i32,
  /// Number of prompt tokens used over the course of the run.
  #[serde(rename = "prompt_tokens")]
  prompt_tokens: i32,
  /// Total number of tokens used (prompt + completion).
  #[serde(rename = "total_tokens")]
  total_tokens: i32
}
