/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunStepDetailsToolCallsCodeObject : Details of the Code Interpreter tool call the run step was involved in.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunStepDetailsToolCallsCodeObject {
  #[serde(rename = "code_interpreter")]
  code_interpreter: crate::models::RunStepDetailsToolCallsCodeObjectCodeInterpreter,
  /// The ID of the tool call.
  #[serde(rename = "id")]
  id: String,
  /// The type of tool call. This is always going to be `code_interpreter` for this type of tool call.
  #[serde(rename = "type")]
  _type: String
}
