/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunObjectRequiredActionSubmitToolOutputs : Details on the tool outputs needed for this run to continue.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunObjectRequiredActionSubmitToolOutputs {
  /// A list of the relevant tool calls.
  #[serde(rename = "tool_calls")]
  tool_calls: Vec<crate::models::RunToolCallObject>
}
