/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunStepDeltaStepDetailsMessageCreationObject : Details of the message creation by the run step.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunStepDeltaStepDetailsMessageCreationObject {
  #[serde(rename = "message_creation")]
  message_creation: Option<crate::models::RunStepDeltaStepDetailsMessageCreationObjectMessageCreation>,
  /// Always `message_creation`.
  #[serde(rename = "type")]
  _type: String
}
