/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunStepDeltaObjectDelta : The delta containing the fields that have changed on the run step.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunStepDeltaObjectDelta {
  /// The details of the run step.
  #[serde(rename = "step_details")]
  step_details: Option<Value>
}
