/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunToolCallObject : Tool call objects

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunToolCallObject {
  #[serde(rename = "function")]
  function: crate::models::RunToolCallObjectFunction,
  /// The ID of the tool call. This ID must be referenced when you submit the tool outputs in using the [Submit tool outputs to run](/docs/api-reference/runs/submitToolOutputs) endpoint.
  #[serde(rename = "id")]
  id: String,
  /// The type of tool call the output is required for. For now, this is always `function`.
  #[serde(rename = "type")]
  _type: String
}
