/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunObject : Represents an execution run on a [thread](/docs/api-reference/threads).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunObject {
  /// The ID of the [assistant](/docs/api-reference/assistants) used for execution of this run.
  #[serde(rename = "assistant_id")]
  assistant_id: String,
  /// The Unix timestamp (in seconds) for when the run was cancelled.
  #[serde(rename = "cancelled_at")]
  cancelled_at: i32,
  /// The Unix timestamp (in seconds) for when the run was completed.
  #[serde(rename = "completed_at")]
  completed_at: i32,
  /// The Unix timestamp (in seconds) for when the run was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The Unix timestamp (in seconds) for when the run will expire.
  #[serde(rename = "expires_at")]
  expires_at: i32,
  /// The Unix timestamp (in seconds) for when the run failed.
  #[serde(rename = "failed_at")]
  failed_at: i32,
  /// The identifier, which can be referenced in API endpoints.
  #[serde(rename = "id")]
  id: String,
  #[serde(rename = "incomplete_details")]
  incomplete_details: crate::models::RunObjectIncompleteDetails,
  /// The instructions that the [assistant](/docs/api-reference/assistants) used for this run.
  #[serde(rename = "instructions")]
  instructions: String,
  #[serde(rename = "last_error")]
  last_error: crate::models::RunObjectLastError,
  /// The maximum number of completion tokens specified to have been used over the course of the run.
  #[serde(rename = "max_completion_tokens")]
  max_completion_tokens: i32,
  /// The maximum number of prompt tokens specified to have been used over the course of the run.
  #[serde(rename = "max_prompt_tokens")]
  max_prompt_tokens: i32,
  #[serde(rename = "metadata")]
  metadata: crate::models::Metadata,
  /// The model that the [assistant](/docs/api-reference/assistants) used for this run.
  #[serde(rename = "model")]
  model: String,
  /// The object type, which is always `thread.run`.
  #[serde(rename = "object")]
  object: String,
  #[serde(rename = "parallel_tool_calls")]
  parallel_tool_calls: crate::models::ParallelToolCalls,
  #[serde(rename = "required_action")]
  required_action: crate::models::RunObjectRequiredAction,
  #[serde(rename = "response_format")]
  response_format: crate::models::AssistantsApiResponseFormatOption,
  /// The Unix timestamp (in seconds) for when the run was started.
  #[serde(rename = "started_at")]
  started_at: i32,
  /// The status of the run, which can be either `queued`, `in_progress`, `requires_action`, `cancelling`, `cancelled`, `failed`, `completed`, `incomplete`, or `expired`.
  #[serde(rename = "status")]
  status: String,
  /// The sampling temperature used for this run. If not set, defaults to 1.
  #[serde(rename = "temperature")]
  temperature: Option<f32>,
  /// The ID of the [thread](/docs/api-reference/threads) that was executed on as a part of this run.
  #[serde(rename = "thread_id")]
  thread_id: String,
  #[serde(rename = "tool_choice")]
  tool_choice: crate::models::CreateRunRequestToolChoice,
  /// The list of tools that the [assistant](/docs/api-reference/assistants) used for this run.
  #[serde(rename = "tools")]
  tools: Vec<Value>,
  /// The nucleus sampling value used for this run. If not set, defaults to 1.
  #[serde(rename = "top_p")]
  top_p: Option<f32>,
  #[serde(rename = "truncation_strategy")]
  truncation_strategy: crate::models::CreateRunRequestToolChoice,
  #[serde(rename = "usage")]
  usage: crate::models::RunCompletionUsage
}
