/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RunStepDetailsToolCallsFileSearchObjectFileSearch : For now, this is always going to be an empty object.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunStepDetailsToolCallsFileSearchObjectFileSearch {
  #[serde(rename = "ranking_options")]
  ranking_options: Option<crate::models::RunStepDetailsToolCallsFileSearchRankingOptionsObject>,
  /// The results of the file search.
  #[serde(rename = "results")]
  results: Option<Vec<crate::models::RunStepDetailsToolCallsFileSearchResultObject>>
}
