/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Screenshot : A screenshot action.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Screenshot {
  /// Specifies the event type. For a screenshot action, this property is  always set to `screenshot`.
  #[serde(rename = "type")]
  _type: String
}
