/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Scroll : A scroll action.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Scroll {
  /// The horizontal scroll distance.
  #[serde(rename = "scroll_x")]
  scroll_x: i32,
  /// The vertical scroll distance.
  #[serde(rename = "scroll_y")]
  scroll_y: i32,
  /// Specifies the event type. For a scroll action, this property is  always set to `scroll`.
  #[serde(rename = "type")]
  _type: String,
  /// The x-coordinate where the scroll occurred.
  #[serde(rename = "x")]
  x: i32,
  /// The y-coordinate where the scroll occurred.
  #[serde(rename = "y")]
  y: i32
}
