/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// StaticChunkingStrategyRequestParam : Customize your own chunking strategy by setting chunk size and chunk overlap.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct StaticChunkingStrategyRequestParam {
  #[serde(rename = "static")]
  _static: crate::models::StaticChunkingStrategy,
  /// Always `static`.
  #[serde(rename = "type")]
  _type: String
}
