/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SubmitToolOutputsRunRequest {
  /// If `true`, returns a stream of events that happen during the Run as server-sent events, terminating when the Run enters a terminal state with a `data: [DONE]` message.
  #[serde(rename = "stream")]
  stream: Option<bool>,
  /// A list of tools for which the outputs are being submitted.
  #[serde(rename = "tool_outputs")]
  tool_outputs: Vec<crate::models::SubmitToolOutputsRunRequestToolOutputs>
}
