/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ThreadObject : Represents a thread that contains [messages](/docs/api-reference/messages).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ThreadObject {
  /// The Unix timestamp (in seconds) for when the thread was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The identifier, which can be referenced in API endpoints.
  #[serde(rename = "id")]
  id: String,
  #[serde(rename = "metadata")]
  metadata: crate::models::Metadata,
  /// The object type, which is always `thread`.
  #[serde(rename = "object")]
  object: String,
  #[serde(rename = "tool_resources")]
  tool_resources: crate::models::ModifyThreadRequestToolResources
}
