/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ToolChoiceFunction : Use this option to force the model to call a specific function.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ToolChoiceFunction {
  /// The name of the function to call.
  #[serde(rename = "name")]
  name: String,
  /// For function calling, the type is always `function`.
  #[serde(rename = "type")]
  _type: String
}
