/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TranscriptTextDoneEvent : Emitted when the transcription is complete. Contains the complete transcription text. Only emitted when you [create a transcription](/docs/api-reference/audio/create-transcription) with the `Stream` parameter set to `true`.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TranscriptTextDoneEvent {
  /// The log probabilities of the individual tokens in the transcription. Only included if you [create a transcription](/docs/api-reference/audio/create-transcription) with the `include[]` parameter set to `logprobs`.
  #[serde(rename = "logprobs")]
  logprobs: Option<Vec<crate::models::TranscriptTextDeltaEventLogprobs>>,
  /// The text that was transcribed.
  #[serde(rename = "text")]
  text: String,
  /// The type of the event. Always `transcript.text.done`.
  #[serde(rename = "type")]
  _type: String
}
