/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TranscriptionWord {
  /// End time of the word in seconds.
  #[serde(rename = "end")]
  end: f32,
  /// Start time of the word in seconds.
  #[serde(rename = "start")]
  start: f32,
  /// The text content of the word.
  #[serde(rename = "word")]
  word: String
}
