/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TruncationObject : Controls for how a thread will be truncated prior to the run. Use this to control the intial context window of the run.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TruncationObject {
  /// The number of most recent messages from the thread when constructing the context for the run.
  #[serde(rename = "last_messages")]
  last_messages: Option<i32>,
  /// The truncation strategy to use for the thread. The default is `auto`. If set to `last_messages`, the thread will be truncated to the n most recent messages in the thread. When set to `auto`, messages in the middle of the thread will be dropped to fit the context length of the model, `max_prompt_tokens`.
  #[serde(rename = "type")]
  _type: String
}
