/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UploadPart : The upload Part represents a chunk of bytes we can add to an Upload object.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UploadPart {
  /// The Unix timestamp (in seconds) for when the Part was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  /// The upload Part unique identifier, which can be referenced in API endpoints.
  #[serde(rename = "id")]
  id: String,
  /// The object type, which is always `upload.part`.
  #[serde(rename = "object")]
  object: String,
  /// The ID of the Upload object that this Part was added to.
  #[serde(rename = "upload_id")]
  upload_id: String
}
