/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UrlCitationBody : A citation for a web resource used to generate a model response.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UrlCitationBody {
  /// The index of the last character of the URL citation in the message.
  #[serde(rename = "end_index")]
  end_index: i32,
  /// The index of the first character of the URL citation in the message.
  #[serde(rename = "start_index")]
  start_index: i32,
  /// The title of the web resource.
  #[serde(rename = "title")]
  title: String,
  /// The type of the URL citation. Always `url_citation`.
  #[serde(rename = "type")]
  _type: String,
  /// The URL of the web resource.
  #[serde(rename = "url")]
  url: String
}
