/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UsageTimeBucket {
  #[serde(rename = "end_time")]
  end_time: i32,
  #[serde(rename = "object")]
  object: String,
  #[serde(rename = "result")]
  result: Vec<Value>,
  #[serde(rename = "start_time")]
  start_time: i32
}
