/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// User : Represents an individual `user` within an organization.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct User {
  /// The Unix timestamp (in seconds) of when the user was added.
  #[serde(rename = "added_at")]
  added_at: i32,
  /// The email address of the user
  #[serde(rename = "email")]
  email: String,
  /// The identifier, which can be referenced in API endpoints
  #[serde(rename = "id")]
  id: String,
  /// The name of the user
  #[serde(rename = "name")]
  name: String,
  /// The object type, which is always `organization.user`
  #[serde(rename = "object")]
  object: String,
  /// `owner` or `reader`
  #[serde(rename = "role")]
  role: String
}
