/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct VectorStoreFileBatchObjectFileCounts {
  /// The number of files that where cancelled.
  #[serde(rename = "cancelled")]
  cancelled: i32,
  /// The number of files that have been processed.
  #[serde(rename = "completed")]
  completed: i32,
  /// The number of files that have failed to process.
  #[serde(rename = "failed")]
  failed: i32,
  /// The number of files that are currently being processed.
  #[serde(rename = "in_progress")]
  in_progress: i32,
  /// The total number of files.
  #[serde(rename = "total")]
  total: i32
}
