/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// VectorStoreFileContentResponse : Represents the parsed content of a vector store file.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct VectorStoreFileContentResponse {
  /// Parsed content of the file.
  #[serde(rename = "data")]
  data: Vec<crate::models::VectorStoreFileContentResponseData>,
  /// Indicates if there are more content pages to fetch.
  #[serde(rename = "has_more")]
  has_more: bool,
  /// The token for the next page, if any.
  #[serde(rename = "next_page")]
  next_page: String,
  /// The object type, which is always `vector_store.file_content.page`
  #[serde(rename = "object")]
  object: String
}
