/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// VectorStoreExpirationAfter : The expiration policy for a vector store.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct VectorStoreExpirationAfter {
  /// Anchor timestamp after which the expiration policy applies. Supported anchors: `last_active_at`.
  #[serde(rename = "anchor")]
  anchor: String,
  /// The number of days after the anchor time that the vector store will expire.
  #[serde(rename = "days")]
  days: i32
}
