/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// VectorStoreObject : A vector store is a collection of processed files can be used by the `file_search` tool.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct VectorStoreObject {
  /// The Unix timestamp (in seconds) for when the vector store was created.
  #[serde(rename = "created_at")]
  created_at: i32,
  #[serde(rename = "expires_after")]
  expires_after: Option<crate::models::VectorStoreExpirationAfter>,
  /// The Unix timestamp (in seconds) for when the vector store will expire.
  #[serde(rename = "expires_at")]
  expires_at: Option<i32>,
  #[serde(rename = "file_counts")]
  file_counts: crate::models::VectorStoreObjectFileCounts,
  /// The identifier, which can be referenced in API endpoints.
  #[serde(rename = "id")]
  id: String,
  /// The Unix timestamp (in seconds) for when the vector store was last active.
  #[serde(rename = "last_active_at")]
  last_active_at: i32,
  #[serde(rename = "metadata")]
  metadata: crate::models::Metadata,
  /// The name of the vector store.
  #[serde(rename = "name")]
  name: String,
  /// The object type, which is always `vector_store`.
  #[serde(rename = "object")]
  object: String,
  /// The status of the vector store, which can be either `expired`, `in_progress`, or `completed`. A status of `completed` indicates that the vector store is ready for use.
  #[serde(rename = "status")]
  status: String,
  /// The total number of bytes used by the files in the vector store.
  #[serde(rename = "usage_bytes")]
  usage_bytes: i32
}
