/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct VectorStoreFileContentResponseData {
  /// The text content
  #[serde(rename = "text")]
  text: Option<String>,
  /// The content type (currently only `\"text\"`)
  #[serde(rename = "type")]
  _type: Option<String>
}
