/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// WebSearchToolCall : The results of a web search tool call. See the  [web search guide](/docs/guides/tools-web-search) for more information.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct WebSearchToolCall {
  /// The unique ID of the web search tool call.
  #[serde(rename = "id")]
  id: String,
  /// The status of the web search tool call.
  #[serde(rename = "status")]
  status: String,
  /// The type of the web search tool call. Always `web_search_call`.
  #[serde(rename = "type")]
  _type: String
}
