/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// WebSearchUserLocation : Approximate location parameters for the search.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct WebSearchUserLocation {
  #[serde(rename = "approximate")]
  approximate: crate::models::WebSearchLocation,
  /// The type of location approximation. Always `approximate`.
  #[serde(rename = "type")]
  _type: String
}
